### ISSUE TITLE
JsonReaderException when retrieving documents containing DateTime

### ISSUE THREAD

**Issue by fiLLLip** [bchavez/RethinkDb.Driver#10]
I have the following code:
```
    Cursor<User> result = _table.run<User>(_c.Connection);
    return result.BufferedItems;
```
I only have one document in my database looking like this (raw fetched with web ui):
```
[{"Address":null,"Birthday":{"$reql_type$":"TIME","epoch_time":650937600,"timezone":"+02:00"},"DisplayName":"fiLLLip","Email":"filip@example.com","FirstName":"Filip","LastName":"Tomren","MiddleName":"Andre Larsen","Phone":"+47123455678","Picture":null,"TenantPermissions":null,"id":"aa93ca25-8672-4545-a927-90b9b1249f4c"}]
```
When I run the code supplied I get the following exception:
```
$exception	{"Error reading date. Unexpected token: StartObject. Path 'Birthday', line 1, position 40."} {$4}	Newtonsoft.Json.JsonReaderException
```
With the following stack trace:
```
Newtonsoft.Json.JsonReader.ReadAsDateTimeInternal()
Newtonsoft.Json.Linq.JTokenReader.ReadAsDateTime()
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
Newtonsoft.Json.Linq.JToken.ToObject[T]()
RethinkDb.Driver.Net.Cursor`1.<>c.<get_BufferedItems>b__17_0(JToken t)
System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
RethinkDb.Driver.Net.Cursor`1.get_BufferedItems()
TestSoftware.DataAccess.Database.RethinkDb.UserService.GetAll() UserService.cs: line: 54
TestSoftware.Api.Controllers.UsersController.Get() UsersController.cs: line: 26
```
My `User` object looks like this (BaseModel contains an id field):
```
public class User : BaseModel
    {
        public IList<TenantPermission> TenantPermissions { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Picture { get; set; }
        public DateTime Birthday { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Address Address { get; set; }
    }
```
My user object was added with the `RethinkDb.Driver`, and posted with the following through an ASP.NET MVC controller:
```
{
	"Email": "filip@example.com",
	"Phone": "+4712345678",
	"DisplayName": "fiLLLip",
	"FirstName": "Filip",
	"MiddleName": "Andre Larsen",
	"LastName": "Tomren",
	"Birthday": "1990-08-18T00:00:00-00:00"
}
```

**Comment by bchavez** [comment]
Hi @fiLLLip , thanks for reporting this. After examining the Java driver, I think we may have to impose a restriction to use only `DateTimeOffset`. The older `DateTime` struct doesn't support time-zones. RethinkDB natively supports time-zones as well as the data structure in the Java driver.

Let me know what you think.

**Comment by fiLLLip** [comment]
I went to Google to find some answers, and found this [issue](https://github.com/JamesNK/Newtonsoft.Json/issues/45). It seems like we can make Json.NET convert and preserve timezone into a `DateTime` type.

I mocked up the following test:
```
using System;
using Newtonsoft.Json;

namespace ConsoleApplication2
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var strings = new[]
            {"{\"DateTime\": \"1990-08-18T00:00:00\"}", "{\"DateTime\": \"1990-08-18T00:00:00+03:00\"}", "{\"DateTime\": \"1990-08-18T00:00:00+02:00\"}", "{\"DateTime\": \"1990-08-18T00:00:00+01:00\"}"};
            foreach (var s in strings)
            {
                Console.Out.WriteLine(s);
                var dateTimeOffsetClass = JsonConvert.DeserializeObject<DateTimeOffsetClass>(s);
                Console.Out.WriteLine($"DateTimeOffsetClass: {dateTimeOffsetClass.DateTime}");
                var jsonSerializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    DateParseHandling = DateParseHandling.DateTimeOffset,
                    DateTimeZoneHandling = DateTimeZoneHandling.Utc
                };
                var dateTimeClass = JsonConvert.DeserializeObject<DateTimeClass>(s, jsonSerializerSettings);
                Console.Out.WriteLine($"DateTimeClass: {dateTimeClass.DateTime}");
            }
            Console.In.ReadLine();
        }
    }

    internal class DateTimeClass
    {
        public DateTime DateTime { get; set; }
    }

    internal class DateTimeOffsetClass
    {
        public DateTimeOffset DateTime { get; set; }
    }
}
```

This supplied me with the following result:
```
{"DateTime": "1990-08-18T00:00:00"}
DateTimeOffsetClass: 18.08.1990 00.00.00 +02:00
DateTimeClass: 18.08.1990 00.00.00
{"DateTime": "1990-08-18T00:00:00+03:00"}
DateTimeOffsetClass: 18.08.1990 00.00.00 +03:00
DateTimeClass: 17.08.1990 21.00.00
{"DateTime": "1990-08-18T00:00:00+02:00"}
DateTimeOffsetClass: 18.08.1990 00.00.00 +02:00
DateTimeClass: 17.08.1990 22.00.00
{"DateTime": "1990-08-18T00:00:00+01:00"}
DateTimeOffsetClass: 18.08.1990 00.00.00 +01:00
DateTimeClass: 17.08.1990 23.00.00
```
This can be somewhat misleading, since the timezone is not specified when using `DateTime`. The positive thing about using this approach is that we don't get any errors.

**Comment by bchavez** [comment]
I think we have two kinds of `DateTime`. `DateTimeKind.Utc` and `DateTimeKind.Utc.Local`. The problem is, what does it mean to be local? DB server local `DateTime` time? App local `DateTime`?

When the server presents us with a time zone that is not UTC, and we're trying to stuff it into a DateTime we actually lose zone information back to the application.

I'll look at this a bit later, I have to go in for a meeting soon. :)

**Comment by bchavez** [comment]
we *could* possibly enforce UTC only with `DateTime` when serializing also

**Comment by fiLLLip** [comment]
I think it would be nice to be able to use `DateTime` if you want, and then we could enforce UTC when serializing/deserializing.

I tested now with `DateTimeOffset`, but I got the same error as when using `DateTime`.

**Comment by fiLLLip** [comment]
I added another document to my database, and tried to fetch all again with no success.
When testing even further, it shows that fetching ONE item with `.get()` works perfectly.
It seems like the problem occurs when executing `Cursor<User> result = _r.db(_c.Dbname).table(TableName).run<User>(_c.Connection);` followed by `result.BufferedItems;`.
In my previous post, `_table` hides `_r.db(_c.Dbname).table(TableName)`

**Comment by bchavez** [comment]
Yea, the problem is with `BufferedItems` is the response payload isn't getting passed into the `Converter`.  Like the Java driver, `Converter`s job is to translate ReQL native types `$reql_type$` like a **date** or **time** into deserializable JSON for Newtonsoft's deserialization without `$reql_type$`. The deserializer throws because `DateTime` is expected, but it encounters a native `$reql_type$` that looks like an Object. Hence the unexpected object exception near `Birthdate`.

So, when the bug mentioned above is fixed and `$reql_type$` tokens get converted by `Converter` (the default converter uses `DateTimeOffset` to convert native `$reql_type$` **date and times** because it's the closest BCL type that matches), you get a new exception. The new exception is an invalid conversion between your POCO `DateTime` and `Converter`'s `DateTimeOffset` result).

These two issues bring up an implementation code smell. We have two distinct **ser/deser**ialization steps:

1. The Java/C# driver's `Converter.java/cs` infrastructure. Primarily used for **deser**ializing & extracting `$reql_type$` into native objects.
2. Newtonsoft's `JsonConverter` infrastructure. Primarily used for **ser**ialization of POCO objects.

My gut felling here is we need to drop the Java driver's `Converter` class and move all `$reql_type$` **ser/deser**ialization into Newtonsoft `JsonConverter`s. This way, we wont ever have to deal with how **Date** and **Times** are **ser/deser**ialized and responsibility will be pushed on to Newtonsoft date & time configuration API. Additionally, we'd also have type information **at final deserialization** time about what the user is requesting, a `DateTime` or a `DateTimeOffset`. Currently, **`Converter`** class doesn't know if the final type is `DateTime` or `DateTimeOffset` (ie: the crux of the issue here); all it does is convert `$reql_type$` into a `DateTimeOffset`.

Let me know your thoughts. I'll need a few days to work this out.

**Comment by fiLLLip** [comment]
My first though is to drop the custom deserializing and use the well proven **ser/deser**ialization in Newtonsoft. I do not know how well it handles the `$reql_type$` objects, but it seems to me that you might have a plan :+1:
How is the **deser**ialization done when using `.get()`? That seems to work just perfect, so maybe a reuse of that logic would work?

**Comment by bchavez** [comment]
@fiLLLip Thanks for your feedback. After giving it a lot of thought, I'm going to make a small architecture change so that the driver embraces the more robust Newtonsoft `JsonConverter` **ser/deser** infrastructure; and we avoid any/all/future edge case issues like this.

Even as it is now, `Converter` uses **JSONPath** to pluck out `$reql_type$` to convert types which already differs from the Java Driver.

Overall, I think when we switch to Newtonsoft's `JsonConverter`, the **ser/deser** process will be more robust. Just need some time to make these changes.

**Comment by fiLLLip** [comment]
Totally agree. Newtonsofts's `JsonConverter` implementation is thoroughly tested, so no need to reinvent the wheel :)

**Comment by bchavez** [comment]
Hi @fiLLLip , 

**alpha6** should be up shortly with the new Newtonsoft `JsonConverter`s implementation.

Minor side effect:

Java driver `FormatOptions` like `time_format: 'raw'` don't make sense anymore. If you want the raw `$reql_type$`, just run a query with `.run<JObject>()` which bypasses the `JsonConverter`s all together.

We're doing pretty good. Only down 2 unit test categories: https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/193/tests

Please close the issue once you've confirmed all is well! Thanks! :+1: Again, thanks for all your help.

**Comment by fiLLLip** [comment]
It looks like something strange is happening with the returned object is deserialized now.
When using **alpha5** the the returned object looks like this (deserialized with RethinkDb.Driver and then serialized with ASP.NET):
```
{
  "TenantPermissions": null,
  "Email": "demo@example.com",
  "Phone": "+4712345678",
  "Picture": null,
  "Birthday": "2015-11-16T07:41:00.986+00:00",
  "DisplayName": "DemoUser",
  "FirstName": "Demo",
  "MiddleName": null,
  "LastName": "User",
  "Address": null,
  "id": "47e64a83-de3f-407d-8a64-343e06b8c285"
}
```

When trying out **alpha6**, the output looks like this (same procedure, nothing changed in code):
```
{
  "TenantPermissions": null,
  "Email": null,
  "Phone": null,
  "Picture": null,
  "Birthday": "2015-11-16T07:41:00.986+00:00",
  "DisplayName": null,
  "FirstName": null,
  "MiddleName": null,
  "LastName": null,
  "Address": null,
  "id": "1b49b6b9-f467-4364-9933-41c113be356a"
}
```

**Comment by fiLLLip** [comment]
I just downloaded **alpha9**, and it seems to work perfectly! Great work @bchavez :+1:
