### ISSUE TITLE
RebirthDB

### ISSUE THREAD

**Issue by thelinuxlich** [bchavez/RethinkDb.Driver#134]
Hey bchavez! We've forked RethinkDB to release a 2.4 version and all drivers will have separate repositories under our organization, discussion here: https://spectrum.chat/rebirthdb

So I'm inviting you to join us, there you can have more visibility for your project, what do you think?

**Comment by bchavez** [comment]
Hi @thelinuxlich,

Thank you for the invitation. We'll definitely take you up on the offer when the time is right for us. Currently, there are a few concerns I have:

* This driver operates under a dual-license. There's a commercial component to that keeps me involved in maintaining and developing this driver. You can read more about it [here](https://github.com/bchavez/RethinkDb.Driver#open-source-and-commercial-licensing) and [here](https://github.com/bchavez/RethinkDb.Driver/issues/131#issuecomment-385315865). So, I'm not sure how well that licensing model will jive with the new **RebirthDB** fork community since this driver is not "truly" open source in the sense of a pure **MIT** or **Apache** license.

* There's a lot of planning and preparation going on for the **C#** driver's **2.4** release. This includes a total re-write of the driver's internal networking code that leverages new framework primitives that **Microsoft** has recently released in **.NET**. The new framework primitives promise some huge gains in performance and memory management. So, moving to a new repo in the middle of this process would complicate things.

* There's a lot of **NuGet** / **Google** / **GitHub** link juice to this repo. Also, I draw much feedback from the **27 watchers** in the repo who are in varying degrees interested in the future of this driver. These people and their opinions are important to me.

#### A plan forward to supporting RebirthDB with C# and .NET:

I'm not against the fork. In fact, we can advertise that we're compatible with **RebirthDB** if it helps adoption of the fork provided the protocols remain somewhat similar. I'll do my best to support **RebirthDB** where I can. However, if the maintenance costs to support both databases increase significantly and the protocols begin to diverge between **RethinkDB** and **RebirthDB** then *that* might be the best time to fork the **C#** driver into a dedicated repository. Ultimately, though, I think it will come down to demand.

So, those are my thoughts. I hope they make some sense. Also, thank you for thinking :thought_balloon: of us! :+1: 

Thanks,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**
