### ISSUE TITLE
Create a method to return result as raw json

### ISSUE THREAD

**Issue by aliprogrammer69** [bchavez/RethinkDb.Driver#139]
i need a method to run query on server and return result as raw json.

e.g : string result = R.Db(DbName).Table(TableName)
                                           .GetAll(R.Args(ids))
                                           .RunAsRowJson(connection);

**Comment by bchavez** [comment]
Hi Ali,

If you need help, please have a look [here in this section of the readme][1] that outlines the help and support options for this driver.

Normally, GitHub issues here are mostly reserved for bug reports and issues surrounding changes to the driver source code.

[1]: https://github.com/bchavez/RethinkDb.Driver#getting-help

**Comment by aliprogrammer69** [comment]
Hi Brian,
Thank for your reply. I just want a method to run query on server and return result as raw json and I can’t find a method like this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bchavez** [comment]
Hi Ali,

Perhaps I closed the issue too soon and probably should have explained a little more.

The proposal for `.RunAsRowJson()` is slightly ambiguous. The `string result` in the query is ambiguous because it requires a discussion to determine what `result` should be in terms of JSON.
```csharp
string result = R.Db(DbName).Table(TableName)
                   .GetAll(R.Args(ids))
                   .RunAsRowJson(connection);
```
* Is `result` the semantic JSON result of the query? 
* Is `result` the raw JSON protocol response that is received from the server?
* What about cursor responses as `result` JSON? Cursor response `results` that bypass the driver internal management can cause memory leaks on the server if opened cursors are not properly driven by the client.
* ... and a whole slew of many other issues as well.

So, the proposal isn't quite as clear cut as it may seem.

What should `.RunAsRowJson()` return? I don't know.

My gut feeling is that you are ***probably*** looking for is the ReQL [`.ToJsonString()`](https://rethinkdb.com/api/java/to_json_string/) method. And this is why I originally suggested carrying the conversation over on Discord or Gitter.im if you need help using it.

Hope that helps,
Brian

**Comment by aliprogrammer69** [comment]
Hi Brain,
Specially Thank for your response and appending time for my problem.

The Proposal for .RunAsRowJson() just is to create a method that returned server result as raw json string.

e.g. we have a table with name “channels”  in rethinkDb which contains object below

{

  *   "access": "private" ,
  *   "admin": {

     *   "id": -110 ,
     *   "name": "deleted account" ,
     *   "user": ""
} ,

  *   "channelId": 30 ,
  *   "dateInsert": "2019-01-09 19:01:22.719054" ,
  *   "dateUpdate": 1550869364 ,
  *   "id": 30 ,
  *   "name": "ch 1" ,
  *   "nextCursor": 17 ,
  *   "time": 1478245932572 ,
  *   "type": "channel"
}

Now I just wanna to receive raw json string from server without any serialize or deserialization.
So .RunAsRowJson() should return server response as json string.

I don’t need to use Cursor, Result or other result types. Just raw string.

Thanks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
