### ISSUE TITLE
check table existence

### ISSUE THREAD

**Issue by eze1981** [bchavez/RethinkDb.Driver#16]
What is the preferred way to check if a table exists in a database?
Using .tableList() ?

Thanks

**Comment by bchavez** [comment]
Hello @eze1981 , sure, you can do `.tableList()` and check if it exists. `.tableList()` the easiest to understand:
```
var result = r.db(DbName).tableList().runAtom<List<string>>(conn);
if( result.Contains("test") )
{
    //exists
}
else
{
    //doesnt exist
}
```
Alternatively, you can have the server check and create a table if it doesn't exist. It's a bit more advanced, but this also works:
```
var result = r.db("mydb").tableList().contains("newTable")
    .do_(tableExists =>
        {
            return r.branch(
                tableExists, /* The test */
                new {tables_created = 0}, /* What to do if  false */
                r.db("mydb").tableCreate("newTable") /* what to do if true */
                );
        }).runResult(conn);
```

`result.TablesCreated` will be 1 or 0, depending if the table existed or not. If it didn't exist, the server will create one. If you want the `config_changes` use `.run<JObject>` instead and probe though the config values you're looking for.

I hope you don't mind, I'm going to close this issue since it's not particularly a problem with the C# driver code...  but feel free to comment further if you need more help understanding the examples above. A great source for general ReQL questions is the freenode `#rethinkdb` community channel. Currently, there's about 114 users online right now. Many are idle, but someone usually answers questions after a few minutes. I'm also in this channel. If you're using windows, a good IRC freenode client is [HexChat](https://hexchat.github.io).

https://github.com/rethinkdb/rethinkdb#need-help

**Comment by bchavez** [comment]
Also, forgot to mention, we have a Gitter.IM channel, like IRC, but specifically for this driver: https://gitter.im/bchavez/RethinkDb.Driver
