### ISSUE TITLE
Support async cancellation

### ISSUE THREAD

**Issue by quentez** [bchavez/RethinkDb.Driver#30]
I can see that some of the base methods used by the driver have support for cancellation tokens, but these are not exposed at the public level for methods like `RunAsync<T>`. It would be nice if every Async method could be cancelled, especially the long running ones like `MoveNextAsync()`.

**Comment by bchavez** [comment]
Hi there @quentez , thank you for bringing up the issue. You're absolutely right, supporting `CancellationToken` is currently on my "todo" list, see: https://github.com/bchavez/RethinkDb.Driver/issues/26#issuecomment-183034490

I just got done with a huge refactoring of the of the public API to follow C#/.NET conventions and pushed `2.2.5-beta-3` bits out the door. I'll have to tackle this next time tho. I'll try to work on it this weekend. But I'm bit tired atm and need to eat dinner. :fork_and_knife: =)

**Comment by quentez** [comment]
Awesome! I didn't see that comment, sorry. Fantastic work on the refactoring, I've already updated to the new version and definitely prefer the new conventions. Enjoy dinner ;) !

**Comment by bchavez** [comment]
Hey @quentez , the Async API should be fully implemented now. First class support for `CancellationToken`. Give it a go. :musical_score:  **v2.2.5**. :+1: Let me know if I missed anything.

PS: Some async APIs like `ConnectAsync` don't handle cancellation because the underlying API doesn't support it.
