### ISSUE TITLE
Inconsistency between AND and OR ReqlExpr methods

### ISSUE THREAD

**Issue by quentez** [bchavez/RethinkDb.Driver#36]
At the moment, the signature for `Or()` on a `ReqlExpr` is:

```csharp
Or(object exprA, params object[] exprs)
```
And for `And()`:
```csharp
And(params object[] exprs)
```

Not only would it be more consistent to have `Or()` behave like `And()`, it would also make it easier to build these kinds of expressions dynamically from a collection of items.

**Comment by bchavez** [comment]
Hi @quentez ,

Thanks for bringing up the issue, I appreciate it. You raise an interesting issue. As far as I can tell, I don't think there is any reason the signatures for `And` and `Or` to be different. Although the Java driver has similar method signatures:

[`ReqlExpr.java`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/gen/ast/ReqlExpr.java#L1746)
```
    public Or or(Object exprA, Object... exprs) {
      ....
    }
    public And and(Object... exprs) {
      ....
    }
```

At least for now, there isn't anything I can do until I can get another set of eyes to look at the method signatures in the Java source. I think this needs to be investigated further upstream in Java Driver since our C# AST is sourced from Java's metadata.

ping: @deontologician

**Comment by quentez** [comment]
Thanks for the quick fix :) !
