### ISSUE TITLE
Nuget compatibility with Xamarin Studio in osx

### ISSUE THREAD

**Issue by samukbg** [bchavez/RethinkDb.Driver#40]
Hi guys, this is maybe a noob question considering i am initiating with c# and xamarin with xamarin forms, when i try to install the nuget package with Xamarin Studio in Mac OSX i get this error message: 
"Could not install package 'RethinkDb.Driver 2.2.10'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

Any tips?
Thanks

**Comment by bchavez** [comment]
Hi Samuel,

Thanks for raising the issue. I really appreciate it. Are you trying to install the driver reference part of a Xamarin mobile project?

From the error message, it seems like the the Xamarin project is probing for a **portable** version of the driver:

```
portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10
```

We don't ship or support portable driver references for mobile devices. Although, this might change in the future due to some recent changes in RethinkDB 2.3 with user authentication support. https://github.com/rethinkdb/rethinkdb/issues/5461

If you're looking to build a stock mono app with Xamarin Studio installing the driver reference should work. I think the proper setup project is listed under "Other Project Items / Mono / MonoMac" somewhere in the new project setup screen.

Also, I'm currently on vacation so I won't be back at work until sometime around April 25th. I apologize for the delay.

Thanks,
Brian

**Comment by samukbg** [comment]
Thanks for the reply, I appreciate it.

Exactly I thought that this driver could work with a Xamarin.Forms PCL project that i am working on, but is there any work around to make it work? Or any RethinkDB C# driver that could work with PCL project (I didn't find any yet)?

Have a nice vacation btw

Thanks,
Sam

**Comment by bchavez** [comment]
Hi Samuel,

I'm not aware of any C# RethinkDB driver that can work with PCL projects.

I don't see an immediate workaround for this driver except actually targeting PCL and looking what breaks. My guess is `TcpClient`, some concurrent data structures, and threading issues might need to be resolved. Most of the cross platform code we have now is in [`CrossPlatform.cs`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Utils/CrossPlatform.cs) with all the preprocessor directives for .NET Core and Full Framework.

We have a  "getting started" driver development guide that should help in case you want to compile the driver manually: https://github.com/bchavez/RethinkDb.Driver/wiki/Getting-Started

Hope that helps!
Brian

**Comment by aleksanderwaagr** [comment]
I am having the same issue when trying to use RethinkDb.Driver in a Xamarin PCL project. I would greatly appreciate an update to support authentication and PCL support. Looks like authentication is already implemented in the Java version? Keep up the great work! :)

**Comment by cecilphillip** [comment]
Respectfully, there really should be a layer between your database and your mobile app to mitigate security issues.

Just my opinion though...

**Comment by bchavez** [comment]
Alrighty, so ... @samukbg , @aleksanderwaagr, @mehmetafsinyuce (UWP):  I don't know if this will work and solves your issue, but **RethinkDb.Driver** is now compatible with `netstandard1.3` which according to [this chart](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) ***should*** make **Xamarin Platform** light up.

No guarantees tho... :warning: phones may burn up into piles of ashes! :fire: :fire_engine: :sunglasses:

`netstandard1.3` bits are here: [`RethinkDb.Driver v2.3.2-beta-1`](https://www.nuget.org/packages/RethinkDb.Driver/2.3.2-beta-1)

And if it works, hit that close button with vengeance! :+1: 

Burn it down: https://www.youtube.com/watch?v=dxytyRy-O1k
