### ISSUE TITLE
Single connections have an Open property. Consider adding this property to connection pools.

### ISSUE THREAD

**Issue by jjonesrs** [bchavez/RethinkDb.Driver#83]
At the moment, there isn't a way to determine if any or all connections in a `ConnectionPool` are open.

This would be useful for testing whether a connection attempt succeeded and for whether a query can be sent across the wire.

**Comment by bchavez** [comment]
Hey, @jjonesrs. Your issue should be fixed now.

Your request is now in [**`v2.3.11`**](https://www.nuget.org/packages/RethinkDb.Driver/2.3.11) and available on NuGet. `ConnectionPool.AnyOpen` to check if any node is available in the host pool to serve up the query.

:thought_balloon: :calendar: [***"Something's missing from the mind... Think about it everyday since '95."***](https://www.youtube.com/watch?v=S3vDBPO0FcQ)
