### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by stefanprodan** [bchavez/RethinkDb.Driver#93]
I'm having the following situation: at app start I'm opening a connection and use it as singleton in my code. Before I run a query, I check if the connection is still open , if not, I call reconnect.

After 20 minutes of inactivity, the `conn.Open` returns `true` but when I run a query I'm getting this error:

```
Write Query failed for Token 6. Exception: Unable to write data to the transport connection: Broken pipe.
Response Pump: IOException - Unable to read data from the transport connection: Connection reset by peer. The connection can no longer be used. ResponsePump is preparing to shutdown.
Cleaning up Response Pump awaiters for rdb-proxy:28015
```

How can I know when to call reconnect if  `conn.Open` returns `true` even if the pipe is broken?

Thanks

**Comment by bchavez** [comment]
Hi @stefanprodan 

What OS and runtime?

**Comment by stefanprodan** [comment]
The RethinkDb cluster in running on Docker Swarm, RethinkDb version is  2.3.4.
The aspnetcore app is also runing in the same docker swarm.

**Comment by stefanprodan** [comment]
Here is the connection [logic](https://github.com/stefanprodan/aspnetcore-dockerswarm/blob/master/src/RethinkDbLogProvider/RethinkDbConnectionFactory.cs#L21) and I'm using it in like [this](https://github.com/stefanprodan/aspnetcore-dockerswarm/blob/master/src/LogWatcher/Hubs/LogHub.cs#L25)

**Comment by bchavez** [comment]
Hey @stefanprodan ,

Looking at the code path, it appears we have:
`Connection.Open -> SocketWrapper.Open -> Socket.Connected`

* `Connection.Open` is our code.
* `SocketWrapper.Open` is our code.
* `Socket.Connected` is the provided by the .NET runtime/framework.

It's straight through call down to `Socket.Connected` without anything fancy.

Checking the source code for [`Socket` here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L368):
```
// Gets the connection state of the Socket. This property will return the latest
// known state of the Socket. When it returns false, the Socket was either never connected
// or it is not connected anymore. When it returns true, though, there's no guarantee that the Socket
// is still connected, but only that it was connected at the time of the last IO operation.
public bool Connected
```
Not much we can do about it unless there's some other `Socket` API call to determine connectedness that we should be using...

I'm open to any ideas ..... :thought_balloon: 

:thought_balloon: :calendar: [***"Something's missing from the mind... Think about it everyday since '95."***](https://www.youtube.com/watch?v=S3vDBPO0FcQ)

**Comment by stefanprodan** [comment]
Maybe you could change the `CheckOpen` function to ping the RethinkDb server instead of just checking the `Socket` state. Or better create a new method named Ping that will do the round-trip to server and back.

**Comment by bchavez** [comment]
The only thing I can think of is, `try{}catch{}` the query and reconnect if there's some kind of exception.

ie:
```
try{
 //run query
}
catch{
  //_now_ that you've attempted an IO operation
  //could you check here? maybe will conn.Open be false this time?
  //if so, then attempt to reconnect
}
```

As for ping, I think we have something currently `Connection.Server()` which does ping the server about server meta info like server name and stuff. Could you wrap that one in an extension method?

I'm still not sure how I feel about a dedicated `Ping` method, though. It seems we'd still be in the same situation (but less so) because wouldn't know if the connection is legitimately open or not until we actually try to write something (ie: the actual query).

Let me know your thoughts....

:thought_balloon: :mag: [***"I want to know... what you're thinking..."***](https://www.youtube.com/watch?v=ijAYN9zVnwg)

**Comment by stefanprodan** [comment]
OK but If I do that then I will lose the changefeed items.

**Comment by bchavez** [comment]
Hey @stefanprodan , looking at the [connection logic](https://github.com/stefanprodan/aspnetcore-dockerswarm/blob/master/src/RethinkDbLogProvider/RethinkDbConnectionFactory.cs#L21), my gut feeling is that it's the wrong singleton-pattern for reconnecting. Try the `try{}catch{ open? reconnect}` pattern.

@stefanprodan in what way do you lose changefeed items with `try{}catch{}`? Could you explain more? Do you have some more code I can look at?

**Comment by stefanprodan** [comment]
Here is my changfeed [code](https://github.com/stefanprodan/aspnetcore-dockerswarm/blob/master/src/LogWatcher/Hubs/LogChangeHandler.cs)

**Comment by stefanprodan** [comment]
I see that this problems is related to [TCP keepalive](https://github.com/rethinkdb/rethinkdb/issues/4572) but looking at the ConnectInternalAsync you are using [Keep Alive](https://github.com/bchavez/RethinkDb.Driver/blob/113e7ec299735271a80a6e0aefa43ff93e9fbd64/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L100) ...

**Comment by bchavez** [comment]
I'm not sure I see how it breaks the ability to ***use*** changefeed items. Are you thinking that when a connection breaks, you might lose changefeed items that were due inbound? I don't think there's any way around that IIRC, RethinkDB does not support resumable change feeds yet: https://github.com/rethinkdb/rethinkdb/issues/3471

:cloud: :sunny: [**Bassnectar - Chasing Heaven - Into the Sun**](https://www.youtube.com/watch?v=a2BAia075lE)

**Comment by stefanprodan** [comment]
Ah OK, I will stop using change feeds then. 

 I will switch to `try{}catch{ open? reconnect}` pattern, thanks a lot for your help.

**Comment by bchavez** [comment]
If you're looking for a reliable feed that can survive TCP disconnection, I think you have to do a little more application level work. Maybe this will help:

https://github.com/neumino/rethinkdbdash/issues/121#issuecomment-237128712

:cat: :bee: [***"Orange buttercat... Chasing after... The crazy bee..."***](https://www.youtube.com/watch?v=4WO4oSsxlKs)

**Comment by stefanprodan** [comment]
I will try that. Thanks again
